# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
language: objective-c
osx_image: xcode7
notifications:
  email: false
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -project SoundCloudSwift.xcodeproj -scheme "SoundCloudSwift iOS" -sdk iphonesimulator9.0 ONLY_ACTIVE_ARCH=NO | xcpretty -c
- set -o pipefail && xcodebuild test -project SoundCloudSwift.xcodeproj -scheme "SoundCloudSwift OSX" ONLY_ACTIVE_ARCH=NO | xcpretty -c
